spring:
  application:
    name: INFO-SERVICE
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/dev
    username: root
    password: root
  config:
    import: configserver:http://${CONFIG_SERVER_URL:localhost}:9296


okta:
  oauth2:
    issuer: https://dev-36592237.okta.com/oauth2/default
    audience: api://default
    client-id: 0oacv28sym7cFitTr5d7
    client-secret: N4Rq3keNF9Q43Nq5eH-_Sg9ladr8dq2_Ay5M-_K6tqZngHWXhImqB3kweSWnuW1o
    scopes: openid, profile, email, offline_access

server:
  port: 9090




